# Unencrypted secret - DO NOT COMMIT
apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: wasserbilanz
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:XnnCsqqO7A==,iv:EJRqrj0GnXskfP6Hbc7i805BT1vSnXRWloM1FlUv2vs=,tag:U5x7maOaeazxH+Ahhr+tCw==,type:str]
    password: ENC[AES256_GCM,data:pwNyxKufYY816CKk4ag=,iv:nNRW4HIoFYy7qmYAGUfEMHgFp2oOd7KcoVbyrx0V/ME=,tag:lfvRqpHK8JgvsRleVSk+eQ==,type:str]
sops:
    age:
        - recipient: age1zvvmhtmlsltgz6ml7kdlfu8ttkvew8yd4l6dcxyflzq306mvnensh742ut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQnN6ZVAwUFVQNVROZHNE
            eGdGWnREazZXc0tTcm12WkFDekFvUGFYREhVCnRlcEt5Q0pPMWZXZFdHNHpzTGJa
            SEF5ejNTbFZUZ0U0RnNHWm9yaHFCQVUKLS0tIDUwYktOVElJb3Z6NmFUOFNWUTRw
            TXM5cmtsakZxSytKQS9udy9KY3lCazgKs/rqf9NQqeBfsXAMKJl+pih8xQyTXmoW
            jMD/2c0S6F7tRhJ4RN8ekfsBsoF4FXLKKmnlEmfMHp0qcmY5EhrtGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T14:47:03Z"
    mac: ENC[AES256_GCM,data:Oi77jBSJRqpXV8jBOdD7oJKDIHDx71nQk14jrFtdjgdYNWs9XzPiHfgXqtdXCOc02gMYTahqHQpsKv9fUDR7f2FLNuUTPMqqfQ+1Vgjob4x9oSQp3vNkZe8r4/aTD9i73+DopvQUMDQcRafZzm87IlRurBHKq4MVzcWLTiCtYBg=,iv:x3zmaVJL2MFVf3qrmq5bOdwzdJAHiUzwZEo2cllORS8=,tag:sDnmol2c07rzoo8qdhV/fQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
